import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    title: "NagarikSaathi",
    portalSub: "Govt Welfare Scheme Portal",
    home: "Home",
    allSchemes: "All Schemes",
    adminPanel: "Admin Panel",
    howItWorks: "How it Works",
    operatorLogin: "Operator Login",
    enterPassword: "Enter Operator Password",
    accessDashboard: "Access Dashboard",
    incorrectPassword: "Incorrect Password",
    heroTitle: "Schemes Discovery,",
    heroSubTitle: "Simplified for India",
    heroDesc: "Discover government schemes instantly. Designed for operators assisting citizens with document checklists, eligibility, and applications.",
    heroTitle1: "Discover Government Schemes",
    heroTitle2: "Simplified for India",
    heroSubtitle: "Find, screen, and apply for central and state government benefits using your voice or guided eligibility checks.",
    searchPlaceholder: "Ask for schemes (e.g. I am a farmer, I need subsidy...)",
    finding: "Finding the best schemes for you...",
    recommended: "Recommended Schemes",
    recommendedSub: "Based on your search and eligibility criteria, here are the top matching government schemes.",
    resultsFound: "schemes found",
    noSchemes: "No Schemes Found Yet",
    noSchemesSub: "Use the search box, voice input, or category filters above to discover government welfare schemes.",
    offlineBanner: "Offline Mode: Using cached local rules.",
    filterLabel: "Filter:",
    footerTagline: "Empowering Rural India with Voice, AI & Direct Benefit Discovery",
    footerMade: "Made with ❤️ for Bharat",
    aiSaathi: "AI Saathi",
    startChat: "Start Scheme Discovery Chat",
    checkEligibility: "Check Eligibility Screener",
    newChat: "New Chat",
    logout: "Logout",
    loginTitle: "Operator / Citizen Login",
    loginDesc: "Log in to access personalized scheme recommendations based on your profile.",
    registerTitle: "Create Account & Profile",
    registerDesc: "Setup your profile with age, occupation, and state to automatically filter matching schemes.",
    loginBtn: "Sign In",
    registerBtn: "Register & Profile",
    needAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    operatorHeader: "CSC OPERATOR SESSION ACTIVE",
    citizensHelped: "Citizens helped today",
    avgSpeed: "Avg. match speed",
    chatPlaceholder: "Ask a scheme query... (e.g. 'Old age pension MP')",
    voiceNotice: "Voice Input coming soon",
    matchedTitle: "Matched Schemes",
    viewGuide: "View Guide",
    eligibilityTitle: "Eligibility Screener",
    eligibilityDesc: "Input the parameters to run a direct database filter query.",
    stateLabel: "State",
    occLabel: "Occupation",
    genderLabel: "Gender",
    maritalLabel: "Marital Status",
    landLabel: "Land Owned",
    incomeLabel: "Annual Family Income (₹)",
    findSchemes: "Find Matching Schemes",
    verifiedBadge: "Verified",
    sourceLabel: "Source",
    backToList: "Back to List",
    printBtn: "Generate Printable Summary",
    printNamePlaceholder: "Enter Citizen's Name (e.g. Meena Devi)",
    printNotice: "Entering a name prints a personalized checklist for verification.",
    documentsTitle: "Required Document Checklist",
    documentsDesc: "Check off these documents with applicant before starting application.",
    speakBtn: "Listen Summary (Audio)",
    settingsTitle: "Configure API Key",
    saveSettings: "Save Configuration",
    apiSuccess: "API key updated successfully!",
    apiError: "Failed to configure key.",
    listening: "Listening... Speak now",
    processing: "Processing...",
    speechError: "Could not understand the audio. Please try again.",
    thinking: "AI Sathi is thinking...",
    listenBtn: "Listen",
    stopBtn: "Stop",
    noAudioSupport: "Speech synthesis is not supported on this browser.",
    apiUnavailable: "AI Sathi is temporarily unavailable. Please try again.",
    recognized: "Recognized",
    startVoiceSearch: "Search by Voice",
    operatorMode: "Operator Assist Chat",
    citizenMode: "Citizen Discovery Chat",
    switchMode: "Switch Mode",
    chatGreeting: "NagarikSaathi Chat",
    chatGreetingSub: "Enter details about the citizen's job, state, age, or income in Hindi or English."
  },
  hi: {
    title: "नागरिक साथी",
    portalSub: "कल्याणकारी योजना सहायता मंच",
    home: "होम",
    allSchemes: "सभी योजनाएं",
    adminPanel: "एडमिन पैनल",
    howItWorks: "यह कैसे काम करता है",
    operatorLogin: "ऑपरेटर लॉगिन",
    enterPassword: "ऑपरेटर पासवर्ड दर्ज करें",
    accessDashboard: "डैशबोर्ड खोलें",
    incorrectPassword: "गलत पासवर्ड",
    heroTitle: "सरकारी योजना खोज,",
    heroSubTitle: "अब हुई आसान",
    heroDesc: "सभी सरकारी योजनाओं की खोज करें तुरंत। दस्तावेज़ चेकलिस्ट, पात्रता और आवेदनों के साथ नागरिकों की सहायता के लिए डिज़ाइन किया गया।",
    heroTitle1: "सरकारी योजनाओं की खोज करें",
    heroTitle2: "भारत के लिए सरलीकृत",
    heroSubtitle: "अपनी आवाज़ या निर्देशित पात्रता जांच का उपयोग करके केंद्र और राज्य सरकार के लाभ खोजें, जांचें और आवेदन करें।",
    searchPlaceholder: "योजनाओं के लिए पूछें (जैसे: मैं एक किसान हूँ, मुझे लोन चाहिए...)",
    finding: "आपके लिए सर्वोत्तम योजनाएं खोजी जा रही हैं...",
    recommended: "अनुशंसित योजनाएं",
    recommendedSub: "आपकी खोज और पात्रता विवरण के आधार पर शीर्ष कल्याणकारी योजनाएं।",
    resultsFound: "योजनाएं मिलीं",
    noSchemes: "अभी तक कोई योजना नहीं मिली",
    noSchemesSub: "उन सरकारी कल्याणकारी योजनाओं को खोजने के लिए ऊपर दिए गए खोज बॉक्स, आवाज़ खोज या श्रेणी फ़िल्टर का उपयोग करें।",
    offlineBanner: "ऑफलाइन मोड: कैश किए गए स्थानीय नियमों का उपयोग हो रहा है।",
    filterLabel: "फ़िल्टर:",
    footerTagline: "आवाज़, AI और सीधे लाभ खोज से ग्रामीण भारत को सशक्त बनाना",
    footerMade: "भारत के लिए ❤️ के साथ बनाया गया",
    aiSaathi: "AI साथी",
    startChat: "योजना खोज चैट शुरू करें",
    checkEligibility: "योग्यता जांचें",
    newChat: "नई चैट",
    logout: "लॉगआउट",
    loginTitle: "ऑपरेटर / नागरिक लॉगिन",
    loginDesc: "अपने प्रोफाइल के आधार पर व्यक्तिगत योजना सुझावों के लिए लॉग इन करें।",
    registerTitle: "खाता और प्रोफाइल बनाएं",
    registerDesc: "योजनाओं को स्वचालित रूप से फ़िल्टर करने के लिए आयु, व्यवसाय और राज्य के साथ प्रोफ़ाइल सेट करें।",
    loginBtn: "साइन इन करें",
    registerBtn: "पंजीकरण और प्रोफाइल",
    needAccount: "खाता नहीं है?",
    haveAccount: "पहले से खाता है?",
    operatorHeader: "सीएससी ऑपरेटर सत्र सक्रिय",
    citizensHelped: "आज मदद किए गए नागरिक",
    avgSpeed: "औसत मिलान गति",
    chatPlaceholder: "योजना के बारे में पूछें... (उदा. 'बुढ़ापा पेंशन मध्य प्रदेश')",
    voiceNotice: "आवाज इनपुट जल्द आ रहा है",
    matchedTitle: "मेल खाती योजनाएं",
    viewGuide: "विवरण देखें",
    eligibilityTitle: "योग्यता जांच (स्क्रीनर)",
    eligibilityDesc: "सीधे डेटाबेस से मिलान करने के लिए मापदंड दर्ज करें।",
    stateLabel: "राज्य",
    occLabel: "व्यवसाय",
    genderLabel: "लिंग",
    maritalLabel: "वैवाहिक स्थिति",
    landLabel: "भूमि स्वामित्व",
    incomeLabel: "वार्षिक पारिवारिक आय (₹)",
    findSchemes: "योजनाएं खोजें",
    verifiedBadge: "सत्यापित",
    sourceLabel: "स्रोत",
    backToList: "सूची पर वापस जाएं",
    printBtn: "प्रिंट योग्य सारांश निकालें",
    printNamePlaceholder: "नागरिक का नाम दर्ज करें (उदा. मीना देवी)",
    printNotice: "नाम दर्ज करने से सत्यापन के लिए एक व्यक्तिगत चेकलिस्ट प्रिंट होती है।",
    documentsTitle: "आवश्यक दस्तावेज़ चेकलिस्ट",
    documentsDesc: "आवेदन शुरू करने से पहले आवेदक के साथ इन दस्तावेजों की जांच करें।",
    speakBtn: "विवरण सुनें (ऑडियो)",
    settingsTitle: "एपीआई कुंजी कॉन्फ़िगर करें",
    saveSettings: "कुंजी सहेजें",
    apiSuccess: "एपीआई कुंजी सफलतापूर्वक अपडेट हो गई!",
    apiError: "एपीआई कुंजी अपडेट करने में विफल।",
    listening: "सुन रहा हूँ... बोलिए",
    processing: "प्रोसेस हो रहा है...",
    speechError: "ऑडियो समझ नहीं आया। कृपया फिर से प्रयास करें।",
    thinking: "AI साथी सोच रहा है...",
    listenBtn: "सुनें",
    stopBtn: "रोकें",
    noAudioSupport: "आपके ब्राउज़र में ऑडियो सपोर्ट उपलब्ध नहीं है।",
    apiUnavailable: "AI साथी अभी उपलब्ध नहीं है। कृपया दोबारा प्रयास करें।",
    recognized: "पहचाना गया",
    startVoiceSearch: "आवाज़ द्वारा खोजें",
    operatorMode: "ऑपरेटर सहायता चैट",
    citizenMode: "नागरिक योजना खोज चैट",
    switchMode: "मोड बदलें",
    chatGreeting: "नागरिक साथी चैट",
    chatGreetingSub: "नागरिक के व्यवसाय, राज्य, आयु या आय के बारे में हिंदी या अंग्रेजी में विवरण दर्ज करें।"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('appLang');
    if (savedLang) {
      setLang(savedLang);
    }
  }, []);

  const toggleLang = () => {
    const newLang = lang === 'en' ? 'hi' : 'en';
    setLang(newLang);
    localStorage.setItem('appLang', newLang);
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
